# Test against the latest version of this Node.js version
environment:
  nodejs_version: "16"

# Install scripts. (runs after repo cloning)
install:
  - ps: $env:package_version = (Get-Content -Raw -Path package.json | ConvertFrom-Json).version
  - ps: Update-AppveyorBuild -Version "$env:package_version-$env:APPVEYOR_BUILD_NUMBER"
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install

cache:
 - C:\projects\Sunrise-WebServer\node_modules

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm test

build_script:
  - npm run build
  - 7z a dist.zip ./dist/*
  - rm -rf dist

artifacts:
  - path: dist.zip
    name: Sunrise-WebServer

on_success:
  - ps: if ($env:APPVEYOR_REPO_BRANCH -eq "main") {C:\projects\Sunrise-WebServer\build_scripts\discord-webhook.ps1 success $env:DISCORD_WEBHOOK_URL}
on_failure:
  - ps: if ($env:APPVEYOR_REPO_BRANCH -eq "main") {C:\projects\Sunrise-WebServer\build_scripts\discord-webhook.ps1 failure $env:DISCORD_WEBHOOK_URL}

# Not yet!
#deploy_script:
#  - ps: if ($env:APPVEYOR_REPO_BRANCH -eq "main") {C:\projects\Sunrise-WebServer\build_scripts\trigger-redeploy.ps1}
  
